//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkCodeGen.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinkCodeGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 		class [classname] : NativeConstParameterFunction
        ///		{
        ///			public [classname]() : base([paracount])
        ///			{
        ///				para = new List&lt;RunTimeDataType&gt;();
        ///[pushparas]
        ///			}
        ///
        ///			public override bool isMethod
        ///			{
        ///				get
        ///				{
        ///					return true;
        ///				}
        ///			}
        ///
        ///			public override string name
        ///			{
        ///				get
        ///				{
        ///					return &quot;[classname]&quot;;
        ///				}
        ///			}
        ///
        ///			List&lt;RunTimeDataType&gt; para;
        ///			public override List&lt;RunTimeDataType&gt; parameters
        ///			{
        ///				get
        ///				{
        ///					return para;
        ///				}
        ///			}
        ///
        ///			public over [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CtorFunc {
            get {
                return ResourceManager.GetString("CtorFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 		class {0} : NativeFunctionBase
        ///		{
        ///			public {0}()
        ///			{
        ///				para = new List&lt;RunTimeDataType&gt;();
        ///			}
        ///
        ///			public override bool isMethod
        ///			{
        ///				get
        ///				{
        ///					return true;
        ///				}
        ///			}
        ///
        ///			public override string name
        ///			{
        ///				get
        ///				{
        ///					return &quot;{0}&quot;;
        ///				}
        ///			}
        ///
        ///			List&lt;RunTimeDataType&gt; para;
        ///			public override List&lt;RunTimeDataType&gt; parameters
        ///			{
        ///				get
        ///				{
        ///					return para;
        ///				}
        ///			}
        ///
        ///			public override RunTimeDataType returnType
        ///			{
        ///				get
        ///				{
        ///					return  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string EnumCtor {
            get {
                return ResourceManager.GetString("EnumCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 		class {0} : ASRuntime.nativefuncs.NativeConstParameterFunction
        ///		{
        ///			public {0}() : base(2)
        ///			{
        ///				para = new List&lt;RunTimeDataType&gt;();
        ///				para.Add(RunTimeDataType.rt_void);
        ///				para.Add(RunTimeDataType.rt_void);
        ///			}
        ///
        ///			public override bool isMethod
        ///			{
        ///				get
        ///				{
        ///					return true;
        ///				}
        ///			}
        ///
        ///			public override string name
        ///			{
        ///				get
        ///				{
        ///					return &quot;{0}&quot;;
        ///				}
        ///			}
        ///
        ///			List&lt;RunTimeDataType&gt; para;
        ///			public override List&lt;RunTimeDataType&gt; parameters
        ///			{
        ///				get
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string EnumItemBitOr {
            get {
                return ResourceManager.GetString("EnumItemBitOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 		class [classname] : NativeConstParameterFunction
        ///		{
        ///			public [classname]() : base(0)
        ///			{
        ///				para = new List&lt;RunTimeDataType&gt;();
        ///			}
        ///
        ///			public override bool isMethod
        ///			{
        ///				get
        ///				{
        ///					return true;
        ///				}
        ///			}
        ///
        ///			public override string name
        ///			{
        ///				get
        ///				{
        ///					return &quot;[classname]&quot;;
        ///				}
        ///			}
        ///
        ///			List&lt;RunTimeDataType&gt; para;
        ///			public override List&lt;RunTimeDataType&gt; parameters
        ///			{
        ///				get
        ///				{
        ///					return para;
        ///				}
        ///			}
        ///
        ///			public override RunTimeDataType re [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string FieldGetter {
            get {
                return ResourceManager.GetString("FieldGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 		class [classname] : NativeConstParameterFunction
        ///		{
        ///			public [classname]() : base(1)
        ///			{
        ///				para = new List&lt;RunTimeDataType&gt;();
        ///[pushparas]
        ///			}
        ///
        ///			public override bool isMethod
        ///			{
        ///				get
        ///				{
        ///					return true;
        ///				}
        ///			}
        ///
        ///			public override string name
        ///			{
        ///				get
        ///				{
        ///					return &quot;[classname]&quot;;
        ///				}
        ///			}
        ///
        ///			List&lt;RunTimeDataType&gt; para;
        ///			public override List&lt;RunTimeDataType&gt; parameters
        ///			{
        ///				get
        ///				{
        ///					return para;
        ///				}
        ///			}
        ///
        ///			public override RunTi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string FieldSetter {
            get {
                return ResourceManager.GetString("FieldSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 					object arg{argindex};
        ///					if (!stackframe.player.linktypemapper.rtValueToLinkObject(
        ///						argements[{argindex}],
        ///
        ///						stackframe.player.linktypemapper.getLinkType(argements[{argindex}].rtType)
        ///						,
        ///						bin, true, out arg{argindex}
        ///						))
        ///					{
        ///						stackframe.throwCastException(token, argements[{argindex}].rtType,
        ///
        ///							functionDefine.signature.parameters[{argindex}].type
        ///							);
        ///						success = false;
        ///						return;
        ///					} 的本地化字符串。
        /// </summary>
        internal static string LoadArgement {
            get {
                return ResourceManager.GetString("LoadArgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 					{argType} arg{argindex};
        ///
        ///					if (argements[{argindex}].rtType == RunTimeDataType.rt_null)
        ///					{
        ///						arg{argindex} = default({argType});
        ///					}
        ///					else
        ///					{
        ///						LinkObj&lt;{argType}&gt; argObj = (LinkObj&lt;{argType}&gt;)((ASBinCode.rtData.rtObjectBase)argements[{argindex}]).value;
        ///						arg{argindex} = argObj.value;
        ///					} 的本地化字符串。
        /// </summary>
        internal static string LoadStructArgement {
            get {
                return ResourceManager.GetString("LoadStructArgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 				[thisObjtype] _this =
        ///					([thisObjtype])((LinkObj&lt;[thisObjtype]&gt;)((ASBinCode.rtData.rtObjectBase)thisObj).value).value; 的本地化字符串。
        /// </summary>
        internal static string LoadStructThis {
            get {
                return ResourceManager.GetString("LoadStructThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 				[thisObjtype] _this =
        ///					([thisObjtype])((LinkSystemObject)((ASBinCode.rtData.rtObjectBase)thisObj).value).GetLinkData(); 的本地化字符串。
        /// </summary>
        internal static string LoadThis {
            get {
                return ResourceManager.GetString("LoadThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 		class [classname] : NativeConstParameterFunction
        ///		{
        ///			public [classname]() : base([paracount])
        ///			{
        ///				para = new List&lt;RunTimeDataType&gt;();
        ///[pushparas]
        ///			}
        ///
        ///			public override bool isMethod
        ///			{
        ///				get
        ///				{
        ///					return true;
        ///				}
        ///			}
        ///
        ///			public override string name
        ///			{
        ///				get
        ///				{
        ///					return &quot;[classname]&quot;;
        ///				}
        ///			}
        ///
        ///			List&lt;RunTimeDataType&gt; para;
        ///			public override List&lt;RunTimeDataType&gt; parameters
        ///			{
        ///				get
        ///				{
        ///					return para;
        ///				}
        ///			}
        ///
        ///			public over [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MethodFunc {
            get {
                return ResourceManager.GetString("MethodFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 		class [classname] : NativeConstParameterFunction
        ///		{
        ///			public [classname]() : base(0)
        ///			{
        ///				para = new List&lt;RunTimeDataType&gt;();
        ///			}
        ///
        ///			public override bool isMethod
        ///			{
        ///				get
        ///				{
        ///					return true;
        ///				}
        ///			}
        ///
        ///			public override string name
        ///			{
        ///				get
        ///				{
        ///					return &quot;[classname]&quot;;
        ///				}
        ///			}
        ///
        ///			List&lt;RunTimeDataType&gt; para;
        ///			public override List&lt;RunTimeDataType&gt; parameters
        ///			{
        ///				get
        ///				{
        ///					return para;
        ///				}
        ///			}
        ///
        ///			public override RunTimeDataType re [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string StaticFieldGetter {
            get {
                return ResourceManager.GetString("StaticFieldGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 		class [classname] : NativeConstParameterFunction
        ///		{
        ///			public [classname]() : base(1)
        ///			{
        ///				para = new List&lt;RunTimeDataType&gt;();
        ///[pushparas]
        ///			}
        ///
        ///			public override bool isMethod
        ///			{
        ///				get
        ///				{
        ///					return true;
        ///				}
        ///			}
        ///
        ///			public override string name
        ///			{
        ///				get
        ///				{
        ///					return &quot;[classname]&quot;;
        ///				}
        ///			}
        ///
        ///			List&lt;RunTimeDataType&gt; para;
        ///			public override List&lt;RunTimeDataType&gt; parameters
        ///			{
        ///				get
        ///				{
        ///					return para;
        ///				}
        ///			}
        ///
        ///			public override RunTi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string StaticFieldSetter {
            get {
                return ResourceManager.GetString("StaticFieldSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 		class [classname] : NativeConstParameterFunction
        ///		{
        ///			public [classname]() : base([paracount])
        ///			{
        ///				para = new List&lt;RunTimeDataType&gt;();
        ///[pushparas]
        ///			}
        ///
        ///			public override bool isMethod
        ///			{
        ///				get
        ///				{
        ///					return true;
        ///				}
        ///			}
        ///
        ///			public override string name
        ///			{
        ///				get
        ///				{
        ///					return &quot;[classname]&quot;;
        ///				}
        ///			}
        ///
        ///			List&lt;RunTimeDataType&gt; para;
        ///			public override List&lt;RunTimeDataType&gt; parameters
        ///			{
        ///				get
        ///				{
        ///					return para;
        ///				}
        ///			}
        ///
        ///			public over [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string StaticMethodFunc {
            get {
                return ResourceManager.GetString("StaticMethodFunc", resourceCulture);
            }
        }
    }
}
